-- AlterTable: VIES validation snapshot fields on Company and Client
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "viesLastCheckAt" TIMESTAMP(3);
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "viesValid" BOOLEAN;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "viesCountryCode" VARCHAR(2);
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "viesNumberLocal" VARCHAR(64);
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "viesTraderName" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "viesTraderAddress" TEXT;

ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "viesLastCheckAt" TIMESTAMP(3);
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "viesValid" BOOLEAN;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "viesCountryCode" VARCHAR(2);
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "viesNumberLocal" VARCHAR(64);
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "viesTraderName" TEXT;
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "viesTraderAddress" TEXT;
